server:
  port: 8083

spring:
  application:
    name: subscription
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: subscription-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.subscription.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true

subscription:
  topics:
    subscription-created: subscription.created
    payment-charged: payment.charged
    subscription-cancelled: subscription.cancelled
